services:
  # ---------------------------------------------------------------------------
  # BROKER MQTT (Eclipse Mosquitto)
  # ---------------------------------------------------------------------------
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: aquarium-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001" 
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - aquarium-net

  # ---------------------------------------------------------------------------
  # BANCO DE DADOS TEMPORAL (InfluxDB v2)
  # ---------------------------------------------------------------------------
  influxdb:
    image: influxdb:2.7
    container_name: aquarium-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123 
      - DOCKER_INFLUXDB_INIT_ORG=aquarium-project
      - DOCKER_INFLUXDB_INIT_BUCKET=aquarium
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=U5BsEr2zJjNRpNsworbQeMSB2FkNKxaCVht0MSRSENDyTQ5kruGWINxas5B8qHRC4LOovCpKM41mZWfIJXurbQ==
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - aquarium-net

  # ---------------------------------------------------------------------------
  # BACKEND JAVA SPRING
  # ---------------------------------------------------------------------------
  backend:
    build: .
    container_name: aquarium-backend
    depends_on:
      - influxdb
      - mosquitto
    ports:
      - "8080:8080"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - MQTT_BROKER_URI=tcp://mosquitto:1883
      - INFLUXDB_TOKEN=U5BsEr2zJjNRpNsworbQeMSB2FkNKxaCVht0MSRSENDyTQ5kruGWINxas5B8qHRC4LOovCpKM41mZWfIJXurbQ==
      - INFLUXDB_ORG=aquarium-project
      - INFLUXDB_BUCKET=aquarium
    networks:
      - aquarium-net

volumes:
  influxdb_data:
  mosquitto_data:
  mosquitto_log:

networks:
  aquarium-net:
    driver: bridge